export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID";
export const SET_CHAT_MESSAGES = "SET_CHAT_MESSAGES";
export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_ACTIVE_USER = "SET_ACTIVE_USER";
